- name: Provision a VMWare Guest
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    vmware_guest_name: rhel8-demo-2
    vmware_datacenter: "SDDC-Datacenter"
    vmware_folder: "/Workloads/sandbox-w7gqh"
    vmware_cluster_name: Cluster-1
    vmware_templates:
      rhel8: zleblanc-rhel8-tmpl
    # vmware_public_key: ssh-rsa AAAA ...

  tasks:
    - name: Create a virtual machine from a template
      register: r_vmware_guest
      community.vmware.vmware_guest:
        datacenter: "{{ vmware_datacenter }}"
        folder: "{{ vmware_folder }}"
        name: "{{ vmware_guest_name }}"
        state: poweredon
        template: "{{ vmware_templates['rhel8'] }}"
        advanced_settings:
          - key: guestinfo.userdata
            value: "{{ lookup('ansible.builtin.template', 'templates/userdata.j2') | ansible.builtin.b64encode }}"
