- name: Provision a VMWare Guest
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    vmware_guest_name: rhel8-demo-3
    vmware_datacenter: "SDDC-Datacenter"
    vmware_folder: "/Workloads/sandbox-w7gqh"
    vmware_cluster_name: Cluster-1
    vmware_os: rhel8
    vmware_templates:
      rhel8: 
        name: zleblanc-rhel8-tmpl
        userdata: userdata.rhel8.j2
    # vmware_public_key: ssh-rsa AAAA ...

  tasks:
    - name: Create a virtual machine from a template
      register: r_vmware_guest
      community.vmware.vmware_guest:
        datacenter: "{{ vmware_datacenter }}"
        folder: "{{ vmware_folder }}"
        name: "{{ vmware_guest_name }}"
        template: "{{ vmware_templates[vmware_os]['name'] }}"
        validate_certs: false
        hardware:
          memory_mb: "{{ vmware_mem_gb|default(2) * 1024 }}"
          num_cpus: "{{ vmware_cpu_count|default(2) }}"
        advanced_settings:
          - key: guestinfo.userdata
            value: "{{ lookup('ansible.builtin.template', 'templates/' + vmware_templates[vmware_os]['userdata']) | ansible.builtin.b64encode }}"
          - key: guestinfo.userdata.encoding
            value: base64
        state: poweredon
