- name: Provision a VMWare Guest
  hosts: localhost
  tags: deploy
  gather_facts: false
  become: false

  vars:
    vmware_guest_name: ansible-demo-vm
    vmware_guest_subdomain: gf7fr.dynamic.redhatworkshops.io
    vmware_datacenter: "SDDC-Datacenter"
    vmware_folder: "/Workloads/sandbox-gf7fr"
    vmware_cluster_name: Cluster-1
    vmware_os: rhel9
    vmware_templates:
      rhel9: 
        name: zleblanc-rhel9-tmpl
        userdata: userdata.rhel9.j2
    # vmware_public_key: ssh-rsa AAAA ...

  tasks:
    - name: Create a virtual machine from a template
      register: r_vmware_guest
      community.vmware.vmware_guest:
        datacenter: "{{ vmware_datacenter }}"
        folder: "{{ vmware_folder }}"
        name: "{{ vmware_guest_name }}"
        template: "{{ vmware_templates[vmware_os]['name'] }}"
        validate_certs: false
        hardware:
          memory_mb: "{{ vmware_mem_gb|default(2) * 1024 }}"
          num_cpus: "{{ vmware_cpu_count|default(2) }}"
        advanced_settings:
          - key: guestinfo.userdata
            value: "{{ lookup('ansible.builtin.template', 'templates/' + vmware_templates[vmware_os]['userdata']) | ansible.builtin.b64encode }}"
          - key: guestinfo.userdata.encoding
            value: base64
        state: poweredon

    - name: Add to in-memory inventory
      ansible.builtin.add_host:
        name: "{{ vmware_guest_name }}.{{ vmware_guest_subdomain }}"
        groups: new_guest
        ansible_host: "{{ r_vmware_guest['instance']['ipv4'] }}"

- name: Bonus play --> Connect to the newly provisioned guest
  hosts: new_guest
  tags: connect
  become: true
  gather_facts: true

  # vars:
  #   ansible_user: ansible # Use Machine Credential with private key for ansible user

  tasks:
    - name: Debug facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Register the newly-created guest
      delegate_to: localhost
      servicenow.itsm.configuration_item:
        name: "{{ inventory_hostname }}"
        sys_class_name: cmdb_ci_vmware_instance
        ip_address: "{{ public_ip_address }}"
        mac_address: "{{ ansible_default_ipv4['macaddress'] | default(ansible_interfaces[0]['macaddress']) }}"
        other:
          vm_inst_id: "{{ instance_id }}"
          fqdn: "{{ inventory_hostname }}"
          dns_domain: "{{ ansible_domain }}"
          guest_os_fullname: "{{ ansible_distribution }}{{ ansible_distribution_version }}"
          cpus: "{{ processor_vcpus | default(ansible_processor_vcpus) }}"
          memory: "{{ ansible_memtotal_mb }}"
          classification: "{{ instance_type }}"
          location: "{{ placement['availability_zone'] }}"
          justification: "{{ tags['purpose'] }}"
          short_description: "{{ tags['info'] }}"
