---
- name: Gather facts about vmware guest
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: true

  tasks:
    - name: Debug facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
