---
galaxy_info:
  author: Zach LeBlanc
  description: Automation Solution Architect
  company: Red Hat

  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: EL
      versions:
        - "9"

  galaxy_tags: ["httpd", "apache", "web", "rhel"]

dependencies: []
