---
- name: Restart redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: true

- name: Start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
