---
- name: Create Label
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Create Label
      ansible.controller.label:
        name: "{{ label }}"
        organization: "{{ organization }}"

    - name: Post Event
      ansible.builtin.set_stats:
        data:
          labeled_event: "{{ ansible_eda.event['payload'] | combine({ 'aap_label': label }) }}"
