---
- name: Sync Automation Hub repositories
  hosts: localhost
  gather_facts: false

  vars:
    # Alow override in Job Template
    ah_collection_repositories:
      - name: rh-certified
        wait: false
      - name: validated
        wait: false
      - name: community
        wait: false

  tasks:
    - name: Sync rh-certified repo without waiting
      ansible.builtin.include_role:
        name: infra.ah_configuration.collection_repository_sync:
