---
- name: Sync Automation Hub repositories
  hosts: localhost
  gather_facts: false

  vars:
    ah_host: "{{ lookup('ansible.builtin.env', 'AH_HOST') }}"
    ah_username: "{{ lookup('ansible.builtin.env', 'AH_USERNAME') }}"
    ah_password: "{{ lookup('ansible.builtin.env', 'AH_PASSWORD') }}"
    
    # Alow override in Job Template
    ah_collection_repositories:
      - name: rh-certified
        wait: false
      - name: validated
        wait: false
      - name: community
        wait: false

  tasks:
    - name: Sync rh-certified repo without waiting
      ansible.builtin.include_role:
        name: infra.ah_configuration.collection_repository_sync
