---
- name: Start zookeeper
  ansible.builtin.systemd:
    name: zookeeper
    state: started
    enabled: yes

- name: Start kafka
  ansible.builtin.systemd:
    name: kafka
    state: started
    enabled: yes

- name: Start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes