---
- name: Read a secret from Azure Key Vault
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    kv_secret_name: ansible-secret
    kv_uri: https://kv-ansible-demo.vault.azure.net

  tasks:
    - name: Fetch secret from AKV
      register: r_kv_secret
      azure.azcollection.azure_rm_keyvaultsecret_info:
        name: "ansible"
        vault_uri: "{{ kv_uri }}"
