---
- name: Restart postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
    enabled: true

- name: Start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
