---
- name: Restart valkey
  ansible.builtin.systemd:
    name: valkey
    state: restarted
    enabled: true

- name: Start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
