---
kafka_version: "3.7.0" # Specify your desired Kafka version
scala_version: "2.13"  # Specify the Scala version compatible with your Kafka version
kafka_install_dir: "/opt/kafka"
kafka_data_dir: "/var/lib/kafka"
zookeeper_data_dir: "/var/lib/zookeeper" # For internal Zookeeper or KRaft
java_home: "/usr/lib/jvm/jre-11-openjdk" # Adjust based on your Java installation
