---
- name: Send expired snapshots email to {{ owner_email }}
  ansible.builtin.include_role:
    name: send_email
  vars:
    send_email_smtp_to_address: "{{ owner_email }}"
    send_email_smtp_subject: "Ansible Notification: {{ owner_snapshots | length }} Expired Snapshots in Azure"
    send_email_smtp_body: "{{ lookup('template', 'snapshot-email.html.j2') }}"
    send_email_smtp_subtype: html
