plugin: servicenow.itsm.now

# Environment variables for connection details
# SN_HOST="https://example.service-now.com"
# SN_USERNAME="admin"
# SN_PASSWORD="password"

# No expressions here, 1:1 mapping between
# column value and hostvar
columns: 
  - name
  - host_name
  - fqdn
  - ip_address
  - sys_class_name
  - install_status
  - classification
  - vendor
  - os
  - os_version
  - serial_number

query_additional_columns:
  - sys_created_by

keyed_groups:
    # example: sn_class_windows_server
  - key: sys_class_name.replace(" ", "_").lower()
    prefix: sn_class
    # example: sn_os_aix
  - key: os.replace(" ", "_").lower()
    prefix: sn_os

groups:
  sn_ec2_instances: name.startswith("ec2-") or fqdn.startswith("ec2-")

# Use the fqdn (instead of name) as the inventory_hostname
# inventory_hostname_source: fqdn

compose:
  ansible_host: fqdn | ternary(fqdn, ip_address) | ternary(ip_address, name) # precedence fqdn -> ip_adress -> name
  classification: classification | lower
  target_env: lookup('ansible.builtin.env', 'target_env', allow_unsafe=True)

# If using a single filter or combining with OR, query is a nice structure
# query:
#   - os: = AIX
#   - os_version: "!="

# If using a filter that requires AND operations, sysparm_query is necessary
sysparm_query: sys_created_by=zleblanc # plain english: the os is AIX and the os version is defined