---
- name: Hashi Vault per-host password demo
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: false

  pre_tasks:
    - name: Create a temporary file with a specific prefix
      delegate_to: localhost
      no_log: "{{ vault_no_log | default(true) }}"
      register: r_tmp
      ansible.builtin.tempfile:
        state: file
        prefix: "{{ inventory_hostname }}_"

    ### IMPORTANT ###
    # Ensure the secret value (a private key file) ends with a newline
    - name: Populate with per-host SSH key
      delegate_to: localhost
      no_log: "{{ vault_no_log | default(true) }}"
      ansible.builtin.copy:
        content: "{{ lookup('community.hashi_vault.hashi_vault', 'cubbyhole/hosts/' + inventory_hostname + ':ssh') }}"
        dest: "{{ r_tmp.path }}"

    - name: Set ansible credentials for each host
      delegate_to: localhost
      no_log: "{{ vault_no_log | default(true) }}"
      ansible.builtin.set_fact:
        ansible_user: "ec2-user"
        ansible_ssh_private_key_file: "{{ r_tmp.path }}"
        ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - name: Gather facts using per-host secret
      ansible.builtin.setup:
