---
- name: Create EC2 instances
  hosts: localhost
  gather_facts: false

  vars:
    aws_region: us-east-2
    aws_ec2_names: "{{ aws_ec2_names_list.split(',') }}"

  vars_files:
    - vars/create_ec2_infra.yml

  tasks:
    - name: Delete EC2
      loop: "{{ aws_ec2_names }}"
      loop_control:
        loop_var: aws_ec2_name
      ansible.builtin.include_tasks:
        file: tasks/delete_ec2.yml

    - name: Record actions
      ansible.builtin.set_stats:
        data:
          deleted_vms: "{{ deleted_vms | default([]) }}"
          _hosts: "{{ aws_ec2_names_list }}"
...