---
- name: Demo running playbook via ansible-navigator
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Gather information about all instances
      amazon.aws.ec2_instance_info:
