---
- name: Install Applications
  hosts: "{{ _hosts | default('omit') }}"
  gather_facts: false
  become: true

  pre_tasks:
    - name: Wait for connection (3m)
      ansible.builtin.wait_for_connection:
        timeout: 180

    - name: Gather facts
      ansible.builtin.setup:

  roles:
    - role: cloud.apps.kafka
      when: "'kafka' in install_apps"
      vars:
        kafka_mode: "{{ _kafka_mode | default('zookeeper') }}"

    - role: cloud.apps.httpd
      when: "'httpd' in install_apps"

    - role: cloud.apps.cockpit
      when: "'cockpit' in install_apps"

    - role: cloud.apps.postgresql
      when: "'postgresql' in install_apps"

    - role: cloud.apps.redis
      when: "'redis' in install_apps"
