---
- name: Install Applications
  hosts: "{{ _hosts | default('omit') }}"
  gather_facts: false
  become: true

  pre_tasks:
    - name: Wait for connection (3m)
      ansible.builtin.wait_for_connection:
        timeout: 180

    - name: Gather facts
      ansible.builtin.setup:

  tasks:
    - name: Install kafka
      when: "'kafka' in install_apps"
      ansible.builtin.include_role:
        name: cloud.apps.kafka
      vars:
        kafka_mode: "{{ _kafka_mode | default('zookeeper') }}"

    - name: Install httpd
      when: "'httpd' in install_apps"
      ansible.builtin.include_role:
        name: cloud.apps.httpd

    - name: Install cockpit
      when: "'cockpit' in install_apps"
      ansible.builtin.include_role:
        name: cloud.apps.cockpit

    - name: Install postgresql
      when: "'postgresql' in install_apps"
      ansible.builtin.include_role:
        name: cloud.apps.postgresql

    - name: Install valkey
      when: "'valkey' in install_apps"
      ansible.builtin.include_role:
        name: cloud.apps.valkey
