- name: Wait for system to be reachable
  ansible.builtin.wait_for_connection:
    timeout: 600

- name: Gather facts
  ansible.builtin.setup:

- name: Determine OS
  ansible.builtin.set_fact:
    sn_os_name: "{{ (ansible_distribution is search('RedHat')) | ternary('Linux Red Hat', 'Windows') }}"

- name: Create CI in CMDB
  delegate_to: localhost
  register: r_ci_create
  servicenow.itsm.configuration_item:
    name: "{{ inventory_hostname }}"
    sys_class_name: cmdb_ci_server
    ip_address: "{{ ci_ip_address | default(public_ip_address) | default(omit) }}"
    mac_address: "{{ ansible_default_ipv4['macaddress'] | default(ansible_interfaces[0]['macaddress']) }}"
    serial_number: "{{ ci_serial_number | default(instance_id) | default(omit) }}"
    other:
      os: "{{ ci_os_name | default(sn_os_name) | default(omit) }}"
      os_version: "{{ ansible_distribution_version | default(omit) }}"
      ram: "{{ ansible_memtotal_mb | default(omit) }}"
      cpu_count: "{{ ansible_processor_count | default(omit) }}"
      cpu_core_count: "{{ ansible_processor_cores | default(omit) }}"
      vm_inst_id: "{{ ci_instance_id | default(instance_id) | default(omit) }}"
      fqdn: "{{ ci_fqdn | default(public_dns_name) | default(omit) }}"
      guest_os_fullname: "{{ ansible_distribution | default('unknown') }}{{ ansible_distribution_version | default(omit) }}"
      cpus: "{{ ci_cpu_count | default(processor_vcpus) | default(ansible_processor_vcpus) | default(omit) }}"
      memory: "{{ ansible_memtotal_mb | default(omit) }}"
      classification: "{{ ci_classification | default(instance_type) | default(omit) }}"
      location: "{{ ci_location | default(placement['availability_zone']) | default(omit) }}"
      justification: "{{ ci_justification | default(tags['purpose']) | default(omit) }}"
      short_description: "{{ ci_short_description | default(tags['info']) | default('CI created by Ansible vm lifecycle management process') | default(omit) }}"
      assigned_to: "{{ ci_assigned_to | default(tags['assigned_to']) | default(omit) }}"

- name: Set stats
  ansible.builtin.set_stats:
    data: >
      {
        "ci_created": {
          "{{ inventory_hostname }}": {{ r_ci_create.record }}
        }
      }