- name: Merge variables with data
  ansible.builtin.set_fact:
    _create_sc_task_data: "{{ create_sc_task_data | combine(create_sc_task_data_overrides[inventory_hostname]|default({})) }}"

- name: Wait for system to be reachable
  ansible.builtin.wait_for_connection:
    timeout: 600

- name: Create VM in CMDB
  delegate_to: localhost
  register: r_sc_task_create
  servicenow.itsm.api:
    resource: sc_task
    action: post
    data: "{{ _create_sc_task_data }}"
      # short_description: "{{ sctask_short_description | default(omit) }}"
      # description: "{{ sctask_description | default(omit) }}"
      # assigned_to: "{{ sctask_assigned_to | default(omit) }}"
      # status: "{{ sctask_status | default(omit) }}"

- name: Set stats
  ansible.builtin.set_stats:
    data: >
      {
        "sc_task_created": {
          "{{ inventory_hostname }}": "{{ r_sc_task_create.record }}"
        }
      }
