- name: Wait for system to be reachable
  ansible.builtin.wait_for_connection:
    timeout: 600

- name: Update RITM
  delegate_to: localhost
  register: r_ritm_update
  servicenow.itsm.api:
    resource: sc_req_item
    action: patch
    sys_id: "{{ update_ritm_sys_id[inventory_hostname] | default(update_ritm_sys_id) }}"
    data: "{{ update_ritm_data | default({}) | combine(update_ritm_data_overrides[inventory_hostname]|default({})) }}"

- name: Set stats
  ansible.builtin.set_stats:
    data: >
      {
        "ritm_updated": {
          "{{ inventory_hostname }}": {{ r_ritm_update.record }}
        }
      }
