---
- name: Start cockpit
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: true

- name: Start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
