---
- name: CyberArk per-host password demo
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: false

  pre_tasks:
    - name: Set ansible credentials for each host
      ansible.builtin.set_fact:
        ansible_user: "ec2-user"
        ansible_password: "{{ lookup('cyberark.conjur.conjur_variable', 'BotApp/' + inventory_hostname) }}"

  tasks:
    - name: Gather facts using per-host secret
      ansible.builtin.setup:
