---
- name: CyberArk per-host password demo
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: false

  pre_tasks:
    - name: password | Set ansible credentials for each host
      when: method == 'password'
      no_log: "{{ cyberark_no_log | default(true) }}"
      ansible.builtin.set_fact:
        ansible_user: "ec2-user"
        ansible_password: "{{ lookup('cyberark.conjur.conjur_variable', 'BotApp/' + inventory_hostname) }}"
        ansible_python_interpreter: "{{ ansible_playbook_python }}"

    - name: ssh key | Create a temporary file with a specific prefix
      when: method == 'sshkey'
      delegate_to: localhost
      no_log: "{{ cyberark_no_log | default(true) }}"
      register: r_tmp
      ansible.builtin.tempfile:
        state: file
        prefix: "{{ inventory_hostname }}_"

    ### IMPORTANT ###
    # Ensure the secret value (a private key file) ends with a newline
    - name: ssh key | Populate with per-host SSH key
      when: method == 'sshkey'
      delegate_to: localhost
      no_log: "{{ cyberark_no_log | default(true) }}"
      ansible.builtin.copy:
        content: "{{ lookup('cyberark.conjur.conjur_variable', 'BotApp/' + inventory_hostname) }}"
        dest: "{{ r_tmp.path }}"

    - name: ssh key | Set ansible credentials for each host
      when: method == 'sshkey'
      delegate_to: localhost
      no_log: "{{ cyberark_no_log | default(true) }}"
      ansible.builtin.set_fact:
        ansible_user: "ec2-user"
        ansible_ssh_private_key_file: "{{ r_tmp.path }}"
        ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - name: Gather facts using per-host secret
      ansible.builtin.setup:
