---
- name: Create in-memory inventory for failure demo
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Create in-memory test inventory
      loop: ["host_one", "host_two", "host_three"]
      ansible.builtin.add_host:
        hostname: "{{ item }}"
        groups: local_three
        ansible_connection: local

- name: Run failing tasks across in-memory hosts
  hosts: local_three
  gather_facts: false
  become: false

  tasks:
    - name: Task one
      ansible.builtin.assert:
        that: inventory_hostname != 'host_one'
        fail_msg: You fell victim to one of the classic blunders

    - name: Task two
      ansible.builtin.assert:
        that: inventory_hostname != 'host_two'
        fail_msg: You're gonna need a bigger server

    - name: Task three
      ansible.builtin.assert:
        that: inventory_hostname != 'host_three'
        fail_msg: There have always been ghosts in this machine
