---
- name: Create in-memory host
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Add host
      ansible.builtin.add_host:
        name: demo_host
        ansible_host: "192.168.0.120"
        ansible_user: zach

- name: Automate host
  hosts: demo_host
  gather_facts: true

  tasks:
    - name: Debug ansible facts
      ansible.builtin.debug:
        var: ansible_facts
