---
- name: Hashi Vault per-host password demo
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: false

  vars:
    secret_container: "cubbyhole/ansible"
    vault_no_log: "{{ vault_secure_logging | bool | default(true) }}"

  pre_tasks:
    - name: Lookup per-host credentials | password
      when: method == 'password'
      no_log: "{{ vault_no_log | default(true) }}"
      ansible.builtin.set_fact:
        ansible_user: "ec2-user"
        ansible_password: "{{ lookup('community.hashi_vault.hashi_vault', secret_container + '/' + inventory_hostname + ':ssh') }}"

    - name: Lookup per-host credentials | sshkey
      when: method == 'sshkey'
      block:
        - name: Create a temporary file with a specific prefix
          delegate_to: localhost
          no_log: "{{ vault_no_log | default(true) }}"
          register: r_tmp
          ansible.builtin.tempfile:
            state: file
            prefix: "{{ inventory_hostname }}_"

        ### IMPORTANT ###
        # Ensure the secret value (a private key file) ends with a newline
        - name: Populate with per-host SSH key
          delegate_to: localhost
          no_log: "{{ vault_no_log | default(true) }}"
          ansible.builtin.copy:
            content: "{{ lookup('community.hashi_vault.hashi_vault', secret_container + '/' + inventory_hostname + ':ssh') }}"
            dest: "{{ r_tmp.path }}"

        - name: Set ansible credentials for each host
          delegate_to: localhost
          no_log: "{{ vault_no_log | default(true) }}"
          ansible.builtin.set_fact:
            ansible_user: "ec2-user"
            ansible_ssh_private_key_file: "{{ r_tmp.path }}"

  tasks:
    - name: Gather facts using per-host secret
      ansible.builtin.setup:
