---
- name: Manage Configuration Items
  hosts: "{{ _cmdb_hosts }}"
  gather_facts: true

  tasks:
    - name: Complete CI Management
      ansible.builtin.include_tasks:
        file: "{{ action }}_ci.yml"
...
