---
- name: Manage Change Requests
  hosts: "{{ _hosts }}"
  gather_facts: true

  tasks:
    - name: Complete CR Management
      ansible.builtin.include_tasks:
        file: "{{ action }}_cr.yml"
...
