---
- name: Manage Configuration Items
  hosts: "{{ _hosts }}"
  gather_facts: false

  tasks:
    - name: Complete CI Management
      ansible.builtin.include_tasks:
        file: "tasks/{{ action }}_ci.yml"
...
