---
- name: Manage ServiceNow Resources
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Complete CR Management
      ansible.builtin.include_tasks:
        file: "{{ sn_manage_action | default(action) }}_{{ sn_resource }}.yml"
...
