---
- name: Start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Permanently enable Valkey firewall rule
  ansible.posix.firewalld:
    port: "{{ valkey_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true
