---
- name: Install packages
  ansible.builtin.dnf:
    name:
      - valkey
      - firewalld
      - python3-firewall
    state: present

- name: Configure valkey.conf
  notify: Restart valkey
  ansible.builtin.template:
    src: valkey.conf.j2
    dest: /etc/valkey/valkey.conf
    owner: root
    group: valkey
    mode: "0640"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Manage firewall
  when: valkey_manage_firewall | bool
  ansible.builtin.include_tasks:
    file: tasks/firewall.yml

- name: Ensure services ready
  ansible.builtin.meta: flush_handlers

- name: Ensure valkey is enabled and started
  ansible.builtin.systemd:
    name: valkey
    state: started
    enabled: true
